name: Lint Checks
on: [push]
jobs:
  ci:
    name: Lint using rome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Installing dependencies
        run: yarn install --frozen-lockfile
      - name: Lint rome
        run: yarn rome ci .
